export const sliderData = [
  {
    title: "First Game",
    image: require("../assets/images/homescreen/game-1.jpeg"),
  },
  {
    title: "Second Game",
    image: require("../assets/images/homescreen/game-2.jpeg"),
  },
  {
    title: "Third Game",
    image: require("../assets/images/homescreen/game-3.png"),
  },
];

export const AZUKI = [
  {
    poster: {
      uri: "https://images-ext-1.discordapp.net/external/QEz1Hq9X8vn-3GBUVJ-7xA4J_XKlUKuAxckM1DdNZr0/https/cdn-longterm.mee6.xyz/plugins/reaction_roles/images/893309380815118336/c28ab44f65a6f7a194a5122cbf94dcfdc38d50fc8bcf313dce273d06a6409179.jpeg?width=1196&height=606",
    },
    title: "Spider-Man",
    subtitle: "Marvel",
    isFree: "No",
    price: "$25.99",
    id: "1",
    bluetags: "#announcement #event",
    isDiscord: true,
    date: "2022-08-09 18:00UTC",
  },

  {
    poster: {
      uri: "https://images-ext-1.discordapp.net/external/1ly8VinOWH_VOdY0QEexNh0miF4MQJVvkfXtCcSXfgE/https/azuki.com/twitterimage.jpg?width=983&height=606",
    },
    title: "Battlefield 2042",
    subtitle: "EA",
    isFree: "No",
    price: "$19.99",
    id: "2",
    bluetags: "#event",
    isDiscord: true,
    date: "2022-08-09 18:00UTC",
  },
  {
    poster: {
      uri: "https://images-ext-2.discordapp.net/external/pA7_4GtxMElRbyKuCY3R0uTfO6B7vDcqRTFwtg6VG0U/https/pbs.twimg.com/media/FUMUAQgUAAAiz6T.jpg?width=606&height=607",
    },
    title: "Spider-Man: Miles Morales",
    subtitle: "Marvel",
    isFree: "No",
    price: "$29.99",
    id: "3",
    bluetags: "#voting #event",
    isDiscord: true,
    date: "2022-08-09 18:00UTC",
  },
  {
    poster: {
      uri: "https://images-ext-1.discordapp.net/external/1ly8VinOWH_VOdY0QEexNh0miF4MQJVvkfXtCcSXfgE/https/azuki.com/twitterimage.jpg?width=983&height=606",
    },
    subtitle: "Xbox Game",
    isFree: "No",
    price: "$24.99",
    id: "4",
    bluetags: "#event",
    isDiscord: false,
    date: "2022-08-09 18:00UTC",
  },
  {
    poster: {
      uri: "https://images-ext-1.discordapp.net/external/k3xVwipsUe9Xq8HwXNVNyrqmy8MSKyfoU2YE-0iIUL0/https/pbs.twimg.com/media/FTO4kh9UsAAs_dW.jpg?width=606&height=606",
    },
    title: "Far Cry 6",
    subtitle: "Ubisoft",
    isFree: "No",
    price: "$15.99",
    id: "5",
    bluetags: "#announcement",
    isDiscord: true,
    date: "2022-08-09 18:00UTC",
  },
  {
    poster: {
      uri: "https://images-ext-1.discordapp.net/external/qVNn6Hgey3PApz3ixJjd7uXmlayRVbRZZ5HKj6sQGVI/https/pbs.twimg.com/media/FTO4sd_UsAAspBf.jpg?width=404&height=606",
    },
    title: "God of War: Ragnarok",
    subtitle: "Sony",
    isFree: "No",
    price: "$25.99",
    id: "6",
    bluetags: "#announcement",
    isDiscord: false,
    date: "2022-08-09 18:00UTC",
  },
  {
    poster: {
      uri: "https://media.discordapp.net/attachments/909579416642912276/970751194274357328/unknown.png?width=606&height=606",
    },
    title: "God of War: Ragnarok",
    subtitle: "Sony",
    isFree: "No",
    price: "$25.99",
    id: "7",
    bluetags: "#announcement",
    isDiscord: true,
    date: "2022-08-09 18:00UTC",
  },
];
export const BAYC = [
  {
    poster: {
      uri: "https://images-ext-1.discordapp.net/external/MgnbycrVY5yQRahxps2BVB8xL6K8rixfVpFMTz8sYv0/https/pbs.twimg.com/media/FUsXVx-WUAAR7kx.jpg?width=1078&height=606",
    },
    title: "Spider-Man",
    subtitle: "Marvel",
    isFree: "No",
    price: "$25.99",
    id: "1",
    bluetags: "#announcement #event",
    isDiscord: false,
    date: "2022-08-09 18:00UTC",
  },

  {
    poster: {
      uri: "https://pbs.twimg.com/media/FWSZobGXgAcQVbw?format=jpg&name=medium",
    },
    title: "Battlefield 2042",
    subtitle: "EA",
    isFree: "No",
    price: "$19.99",
    id: "2",
    bluetags: "#event",
    isDiscord: false,
    date: "2022-08-09 18:00UTC",
  },
  {
    poster: {
      uri: "https://images-ext-1.discordapp.net/external/CYcA_JsLOvBrDB92ZfumgjVFSX94LahXUVUn2Q5H_H8/https/pbs.twimg.com/media/FNmpc6FXoAc7GfM.jpg",
    },
    title: "Spider-Man: Miles Morales",
    subtitle: "Marvel",
    isFree: "No",
    price: "$29.99",
    id: "3",
    bluetags: "#voting #event",
    isDiscord: true,
    date: "2022-08-09 18:00UTC",
  },
  {
    poster: {
      uri: "https://images-ext-2.discordapp.net/external/x2eXbX6y6IfEWVm2hryRHw680OE5fJZHHQzX-FKI5jc/https/pbs.twimg.com/media/FJ_UuVWXMAArgAg.jpg%3Alarge?width=694&height=606",
    },
    subtitle: "Xbox Game",
    isFree: "No",
    price: "$24.99",
    id: "4",
    bluetags: "#event",
    isDiscord: true,
    date: "2022-08-09 18:00UTC",
  },
  {
    poster: {
      uri: "https://images-ext-1.discordapp.net/external/fSrCLLPs6HJLI9iNHm5l3BpsVKQeCLPTFaQph2eVpb0/https/play-lh.googleusercontent.com/3yQgqkTmgX6iYMzNuBkRgsVohxBPdLjDv5_RWxKE21Njnd025U-VpgGE4VwhAG-UG1Y",
    },
    title: "Far Cry 6",
    subtitle: "Ubisoft",
    isFree: "No",
    price: "$15.99",
    id: "5",
    bluetags: "#announcement",
    isDiscord: true,
    date: "2022-08-09 18:00UTC",
  },
  {
    poster: {
      uri: "https://images-ext-2.discordapp.net/external/pDcwQ_DLU7FCqJSfejxLopntIBtqbXGaozAJids-JjU/https/play-lh.googleusercontent.com/nOIXHUIVP2xeSdKoKyPaSfXGvtqAYVOtjQyaDoEU-te-ZCHGWyMz16fDETlnZD6rjw",
    },
    title: "God of War: Ragnarok",
    subtitle: "Sony",
    isFree: "No",
    price: "$25.99",
    id: "6",
    bluetags: "#announcement",
    isDiscord: true,
    date: "2022-08-09 18:00UTC",
  },
  {
    poster: {
      uri: "https://images-ext-1.discordapp.net/external/5v14FnTUSeIBsUsJjg6q4tIpIZRXqQAeUwhL_lp0OO8/https/pbs.twimg.com/media/FC1Tl_KWUAEL4kH.jpg%3Alarge?width=569&height=607",
    },
    title: "God of War: Ragnarok",
    subtitle: "Sony",
    isFree: "No",
    price: "$25.99",
    id: "7",
    bluetags: "#announcement",
    isDiscord: true,
    date: "2022-08-09 18:00UTC",
  },
];
export const DOODLES = [
  {
    poster: {
      uri: "https://images-ext-1.discordapp.net/external/JlcCn1s0jRa3FpHhrxzosvNUtOLTTMiFktLHIjR2s0A/https/res.cloudinary.com/dp3ddzkjp/image/upload/v1646074068/Doodles/infographic_15514762ef.jpg?width=1078&height=606",
    },
    title: "Spider-Man",
    subtitle: "Marvel",
    isFree: "No",
    price: "$25.99",
    id: "1",
    bluetags: "#announcement #event",
    isDiscord: true,
    date: "2022-08-09 18:00UTC",
  },

  {
    poster: {
      uri: "https://media.discordapp.net/attachments/906600867698991105/947645233250832394/FMfUIyyWYAI_YPG.png?width=658&height=606",
    },
    title: "Battlefield 2042",
    subtitle: "EA",
    isFree: "No",
    price: "$19.99",
    id: "2",
    bluetags: "#proposal",
    isDiscord: false,
    date: "2022-08-09 18:00UTC",
  },
  {
    poster: {
      uri: "https://media.discordapp.net/attachments/906600867698991105/935432577618165760/image0.png?width=699&height=606",
    },
    title: "Spider-Man: Miles Morales",
    subtitle: "Marvel",
    isFree: "No",
    price: "$29.99",
    id: "3",
    bluetags: "#voting #event",
    isDiscord: true,
    date: "2022-08-09 18:00UTC",
  },
  {
    poster: {
      uri: "https://media.discordapp.net/attachments/906600867698991105/932092047106650122/mascottoy.png?width=603&height=606",
    },
    subtitle: "Xbox Game",
    isFree: "No",
    price: "$24.99",
    id: "4",
    bluetags: "#voting",
    isDiscord: true,
    date: "2022-08-09 18:00UTC",
  },
  {
    poster: {
      uri: "https://media.discordapp.net/attachments/906600867698991105/918555927601373184/unknown.png?width=1209&height=606",
    },
    title: "Far Cry 6",
    subtitle: "Ubisoft",
    isFree: "No",
    price: "$15.99",
    id: "5",
    bluetags: "#mint",
    isDiscord: true,
    date: "2022-08-09 18:00UTC",
  },
  {
    poster: {
      uri: "https://media.discordapp.net/attachments/906600867698991105/918215578509013062/unknown.png?width=1055&height=606",
    },
    title: "God of War: Ragnarok",
    subtitle: "Sony",
    isFree: "No",
    price: "$25.99",
    id: "6",
    bluetags: "#freemint",
    isDiscord: true,
    date: "2022-08-09 18:00UTC",
  },
  {
    poster: {
      uri: "https://pbs.twimg.com/media/FWIJme4UAAE70Rj?format=jpg&name=large",
    },
    title: "God of War: Ragnarok",
    subtitle: "Sony",
    isFree: "No",
    price: "$25.99",
    id: "7",
    bluetags: "#announcement",
    isDiscord: true,
    date: "2022-08-09 18:00UTC",
  },
];

export const freeGames = [
  {
    poster: require("../assets/images/Altos-Odyssey.jpeg"),
    title: "Altos Odyssey",
    subtitle: "Noodlecake Studios",
    isFree: "Yes",
    id: "1",
  },
  {
    poster: require("../assets/images/asphalt-9.jpeg"),
    title: "Asphalt 9",
    subtitle: "Gameloft",
    isFree: "Yes",
    id: "2",
  },
  {
    poster: require("../assets/images/genshin-impact.jpeg"),
    title: "Genshin Impact",
    subtitle: "miHoYo",
    isFree: "Yes",
    id: "3",
  },
  {
    poster: require("../assets/images/fortnite.webp"),
    title: "Fortnite",
    subtitle: "Epic Games",
    isFree: "Yes",
    id: "4",
  },
  {
    poster: require("../assets/images/pokemon-unite.jpeg"),
    title: "Pokémon Unite",
    subtitle: "The Pokémon Company",
    isFree: "Yes",
    id: "5",
  },
  {
    poster: require("../assets/images/diablo-4.jpeg"),
    title: "Diablo 4",
    subtitle: "Blizzard Entertainment",
    isFree: "No",
    id: "6",
  },
];
